# Generated by Django 4.0.6 on 2022-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1),
            preserve_default=False,
        ),
    ]
