# Generated by Django 4.0.6 on 2022-09-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_order_status_cart_cart_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_items',
            new_name='order_items',
        ),
    ]
