# Generated by Django 4.0.6 on 2022-09-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_items',
            new_name='cart_items',
        ),
    ]
