# Generated by Django 4.0.6 on 2022-09-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_order_items_cart_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_items',
            new_name='order_items',
        ),
    ]
