# Generated by Django 4.0.6 on 2022-09-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_order_items'),
        ('cart', '0007_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_items',
            field=models.ManyToManyField(null=True, related_name='cart', to='orders.order'),
        ),
    ]
