# Generated by Django 4.0.6 on 2022-09-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cart_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivery_address',
            field=models.CharField(default='Placeholder', max_length=1000),
            preserve_default=False,
        ),
    ]
