# Generated by Django 4.0.6 on 2022-09-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_startermenu_starter'),
    ]

    operations = [
        migrations.AddField(
            model_name='startermenu',
            name='image',
            field=models.ImageField(blank=True, default='/media/bread.jpeg', null=True, upload_to='media'),
        ),
    ]
