# Generated by Django 4.0.6 on 2022-09-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_startermenu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='startermenu',
            name='image_height',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='startermenu',
            name='image_width',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='startermenu',
            name='image',
            field=models.ImageField(blank=True, default='/media/bread.jpeg', height_field='image_height', null=True, upload_to='media', width_field='image_width'),
        ),
    ]
