# Generated by Django 4.0.6 on 2022-09-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_startermenu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startermenu',
            name='image',
            field=models.ImageField(blank=True, default='bread.jpeg', height_field='image_height', null=True, upload_to='', width_field='image_width'),
        ),
    ]
