# Generated by Django 4.0.6 on 2022-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_startermenu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DessertMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessert', models.CharField(choices=[('Deep fried banana fritters', 'Deep fried banana fritters'), ('Strawberry cheesecake mochi', 'Strawberry cheesecake mochi'), ('Coconut and mint ice cream', 'Coconut and mint ice cream'), ('Seasonal fruit salad', 'Seasonal fruit salad')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, default='bread.jpeg', height_field='image_height', null=True, upload_to='', width_field='image_width')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=100)),
                ('image_width', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrinksMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(choices=[('Homemade lemonade', 'Homemade lemonade'), ('Lychee boba tea', 'Lychee boba tea'), ('Fresh mango & lime juice', 'Fresh mango & lime juice'), ('Water', 'Water')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, default='bread.jpeg', height_field='image_height', null=True, upload_to='', width_field='image_width')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=100)),
                ('image_width', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(choices=[('Grilled sea bass with roasted vegetables', 'Grilled sea bass with roasted vegetables'), ('Classic Burger', 'Classic Burger'), ('Seafood linguine', 'Seafood linguine'), ('Lobster bisque', 'Lobster bisque')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, default='bread.jpeg', height_field='image_height', null=True, upload_to='', width_field='image_width')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=100)),
                ('image_width', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='SidesMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('Truffle fries', 'Truffle fries'), ('Creamy mashed root vegetables', 'Creamy mashed root vegetables'), ('Roasted Mediterranean vegetables', 'Roasted Mediterranean vegetables'), ('House side salad', 'House side salad')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, default='bread.jpeg', height_field='image_height', null=True, upload_to='', width_field='image_width')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=100)),
                ('image_width', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='startermenu',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startermenu',
            name='starter',
            field=models.CharField(choices=[('Fried Calamari with Garlic & Chilli', 'Fried Calamari with Garlic & Chilli'), ('Burrata with Basil Pesto', 'Burrata with Basil Pesto'), ('Roasted aubergine', 'Roasted aubergine'), ('Bread', 'Bread')], max_length=100),
        ),
    ]
