# Generated by Django 4.0.6 on 2022-09-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_customer'),
        ('menu', '0011_alter_startermenu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(choices=[('Fried Calamari with Garlic & Chilli', 'Fried Calamari with Garlic & Chilli'), ('Burrata with Basil Pesto', 'Burrata with Basil Pesto'), ('Roasted aubergine', 'Roasted aubergine'), ('Bread', 'Bread')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='', width_field='image_width')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=100)),
                ('image_width', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name='StarterMenu',
        ),
    ]
