# Generated by Django 4.0.6 on 2022-09-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_mainmenu_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='menu_item',
            field=models.CharField(choices=[('Fried Calamari with Garlic & Chilli', 'Fried Calamari with Garlic & Chilli'), ('Burrata with Basil Pesto', 'Burrata with Basil Pesto'), ('Roasted aubergine', 'Roasted aubergine'), ('Bread', 'Bread'), ('Grilled sea bass with roasted vegetables', 'Grilled sea bass with roasted vegetables'), ('Classic Burger', 'Classic Burger'), ('Seafood linguine', 'Seafood linguine'), ('Lobster bisque', 'Lobster bisque'), ('Deep fried banana fritters', 'Deep fried banana fritters'), ('Strawberry cheesecake mochi', 'Strawberry cheesecake mochi'), ('Coconut and mint ice cream', 'Coconut and mint ice cream'), ('Seasonal fruit salad', 'Seasonal fruit salad'), ('Truffle fries', 'Truffle fries'), ('Creamy mashed root vegetables', 'Creamy mashed root vegetables'), ('Roasted Mediterranean vegetables', 'Roasted Mediterranean vegetables'), ('House side salad', 'House side salad'), ('Homemade lemonade', 'Homemade lemonade'), ('Lychee boba tea', 'Lychee boba tea'), ('Fresh mango & lime juice', 'Fresh mango & lime juice'), ('Water', 'Water')], max_length=100),
        ),
    ]
