# Generated by Django 4.0.6 on 2022-09-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_mainmenu_menu_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DessertMenu',
        ),
        migrations.DeleteModel(
            name='DrinksMenu',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
        migrations.DeleteModel(
            name='SidesMenu',
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='menu_item',
            field=models.CharField(choices=[('Dough Balls', 'Dough Balls'), ('Garlic Pizza Bread ', 'Garlic Pizza Bread '), ('Garlic Pizza Bread with Mozzarella', 'Garlic Pizza Bread with Mozzarella'), ('Garlic Bread with Vegan Mozzarella ', 'Garlic Bread with Vegan Mozzarella '), ('Meatballs', 'Meatballs'), ('Mozzarella Sticks', 'Mozzarella Sticks'), ('Bacon & Cheese Potato Skins', 'Bacon & Cheese Potato Skins'), ('Cheese & Chive Fully Loaded Potato Skins ', 'Cheese & Chive Fully Loaded Potato Skins '), ('Mozzarella & Tomato Salad ', 'Mozzarella & Tomato Salad '), ('BBQ Chicken Wings ', 'BBQ Chicken Wings '), ('Southern Fried Chicken wih BBQ Sauce ', 'Southern Fried Chicken wih BBQ Sauce '), ('Sticky Hot Chicken Wings ', 'Sticky Hot Chicken Wings '), ('Southern Fried Chicken with Hot Sauce ', 'Southern Fried Chicken with Hot Sauce '), ('Classic Beef Burger ', 'Classic Beef Burger '), ('Double Bacon Cheese Burger ', 'Double Bacon Cheese Burger '), ('Classic Cheese Burger ', 'Classic Cheese Burger '), ('Chicken BLT Burger ', 'Chicken BLT Burger '), ('Vegan Burger', 'Vegan Burger'), ('The House Special Burger ', 'The House Special Burger '), ('Classic Chicken Burger ', 'Classic Chicken Burger '), ('Crispy BBQ Chicken Burger ', 'Crispy BBQ Chicken Burger '), ('Beef Lasagne ', 'Beef Lasagne '), ('Meatballs with Spaghetti ', 'Meatballs with Spaghetti '), ('Spaghetti Carbonara ', 'Spaghetti Carbonara '), ("Mac 'N' Cheese", "Mac 'N' Cheese"), ("Ultimate Mac 'N' Cheese with Bacon", "Ultimate Mac 'N' Cheese with Bacon"), ('Spaghetti Bolognese ', 'Spaghetti Bolognese '), ('Spaghetti Arrabbiata ', 'Spaghetti Arrabbiata '), ('Chicken & Prawn Alfredo with Spaghetti ', 'Chicken & Prawn Alfredo with Spaghetti '), ('10 Pepperoni Pizza ', '10 Pepperoni Pizza '), ('10 BBQ Chicken Pizza ', '10 BBQ Chicken Pizza '), ('10 Hawaiian Pizza', '10 Hawaiian Pizza'), ('10 Vegan Margherita Pizza ', '10 Vegan Margherita Pizza '), ('10 Cajun Chicken Pizza ', '10 Cajun Chicken Pizza '), ('10 Margherita Pizza ', '10 Margherita Pizza '), ('15 Margherita Pizza ', '15 Margherita Pizza '), ('15 Cajun Chicken Pizza', '15 Cajun Chicken Pizza'), ('15 Pepperoni Pizza ', '15 Pepperoni Pizza '), ('15 BBQ Chicken Pizza ', '15 BBQ Chicken Pizza '), ('15 Hawaiian Pizza ', '15 Hawaiian Pizza '), ('15 Vegan Margherita Pizza ', '15 Vegan Margherita Pizza '), ('Sweet Potato Fries ', 'Sweet Potato Fries '), ('Onion Rings ', 'Onion Rings '), ('Greens ', 'Greens '), ('Fries ', 'Fries '), ('Corn on the Cob ', 'Corn on the Cob '), ('Side Salad ', 'Side Salad '), ('Coleslaw ', 'Coleslaw '), ('Beans', 'Beans'), ('Tea', 'Tea'), ('Coffee', 'Coffee'), ('Coke', 'Coke'), ('Fanta', 'Fanta'), ('Sprite', 'Sprite'), ('Orange Juice', 'Orange Juice'), ('Water', 'Water')], max_length=100),
        ),
    ]
