# Generated by Django 4.0.6 on 2022-07-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_startermenu_starterorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='starterorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
