# Generated by Django 4.0.6 on 2022-07-12 15:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_starterorder_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starterorder',
            name='starter',
        ),
        migrations.AddField(
            model_name='starterorder',
            name='starter_order',
            field=models.CharField(choices=[('garlic & chilli calamari', Decimal('7.99'))], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
