# Generated by Django 4.0.6 on 2022-07-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0004_remove_starterorder_starter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starterorder',
            name='price',
        ),
        migrations.AlterField(
            model_name='starterorder',
            name='starter_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.startermenu'),
        ),
    ]
