# Generated by Django 4.0.6 on 2022-07-13 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0005_remove_starterorder_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starterorder',
            name='starter_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.startermenu'),
        ),
    ]
