# Generated by Django 4.0.6 on 2022-07-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_cart_order_items_cart_order_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['customer']},
        ),
    ]
