# Generated by Django 4.0.6 on 2022-07-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_startermenu_starter'),
        ('orders', '0009_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_items',
            field=models.ManyToManyField(related_name='carts', to='orders.starterorder'),
        ),
        migrations.RemoveField(
            model_name='starterorder',
            name='starter_order',
        ),
        migrations.AddField(
            model_name='starterorder',
            name='starter_order',
            field=models.ManyToManyField(related_name='starter_orders', to='menu.startermenu'),
        ),
    ]
