# Generated by Django 4.0.6 on 2022-07-14 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_startermenu_starter'),
        ('orders', '0010_alter_cart_options_remove_cart_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starterorder',
            name='starter_order',
        ),
        migrations.AddField(
            model_name='starterorder',
            name='starter_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.startermenu'),
        ),
    ]
