# Generated by Django 4.0.6 on 2022-07-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_startermenu_starter'),
        ('orders', '0013_remove_cart_order_items_cart_order_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_items',
            field=models.ManyToManyField(related_name='cart', to='menu.startermenu'),
        ),
    ]
