# Generated by Django 4.0.6 on 2022-09-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
    ]
