# Generated by Django 4.0.6 on 2022-09-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_mainmenu_delete_startermenu'),
        ('orders', '0018_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='order', to='menu.mainmenu'),
        ),
    ]
